### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by GTP95** [mopidy/libspotify-deb#5]
I was trying to install mopidy's extension to use Spotify on a Raspberry Pi 3 running a 64bit DietPi image, but I can't use your repo to install libstotify-deb as it doesn't support the arm64 architecture. Would it be possible to also add support for that?
Thank you for your availabillity

**Comment by kingosticks** [comment]
This is not possible, see https://github.com/jodal/pyspotify/issues/207
